baseURL: https://family.sigler.io/
languageCode: en-us
title: Family Media
theme: papermod
env: production
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  description: "Family media, you know... for the family."
  ShowToc: false
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: photos
      url: /photos/
      weight: 10
    - identifier: videos
      name: videos
      url: /videos/
      weight: 20
      #deployment:
      #  targets:
      #    name: aws
      #    url: "s3://is-static-web-hosting?prefix=/notes.improvisedscience.org/&region=us-east-1"
      #    cloudFrontDistributionID: E1YRTMBAIVJ37E
